"""chg buildtask

Revision ID: 023db0559c78
Revises: fe5a54033dde
Create Date: 2026-10-03 15:36:10.345890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023db0559c78'
down_revision: Union[str, Sequence[str], None] = 'fe5a54033dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('build_tasks', sa.Column('result_path', sa.Text(), nullable=True))
    op.add_column('build_tasks', sa.Column('filename', sa.String(length=200), nullable=True))
    op.create_foreign_key('build_tasks_user_id_fkey', 'build_tasks', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('build_tasks_user_id_fkey', 'build_tasks', type_='foreignkey')
    op.drop_column('build_tasks', 'filename')
    op.drop_column('build_tasks', 'result_path')
    op.drop_column('build_tasks', 'user_id')
    # ### end Alembic commands ###
