"""add User email

Revision ID: fe5a54033dde
Revises: 5c2689131e99
Create Date: 2026-10-02 21:40:58.779381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5a54033dde'
down_revision: Union[str, Sequence[str], None] = '5c2689131e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
